CREATE TABLE IF NOT EXISTS ACCOUNT (
       ACCOUNT_NUMBER INT NOT NULL AUTO_INCREMENT,
       CUSTOMER_ID INT NOT NULL,
       STATUS ENUM('ENABLED', 'DISABLED') NOT NULL DEFAULT 'ENABLED',
       PRIMARY KEY (ACCOUNT_NUMBER)
);