CREATE TABLE IF NOT EXISTS CARD (
            CARDID INT NOT NULL AUTO_INCREMENT,
            CARDNUMBER VARCHAR(255) NOT NULL UNIQUE,
            CARDCLIENTNAME VARCHAR(255) NOT NULL,
            CARDTYPE ENUM('PHYSICAL', 'VIRTUAL') DEFAULT NULL,
            CVV VARCHAR(4) NOT NULL,
            ACCOUNT_ID INT NOT NULL,
            STATUS ENUM('ENABLED', 'DISABLED') NOT NULL DEFAULT 'DISABLED',
            ISSUEDATE DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            DELIVERYDATE DATE DEFAULT NULL,
            EXPIRATIONDATE DATE NOT NULL,
            PRIMARY KEY (CARDID)
);